apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: suenara/myapp:1
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
          # ConfigMap values
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: APP_ENV
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: LOG_LEVEL
          - name: DEBUG_MODE
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: DEBUG_MODE
          # Secret values
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: myapp-secrets
                key: API_KEY
                optional: false
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myapp-secrets
                key: DB_PASSWORD
                optional: false
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: logs-volume
        persistentVolumeClaim:
          claimName: myapp-logs-pvc