apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
  labels:
    app: myapp
type: Opaque
data:
  # Base64 encoded values
  # echo -n "your-api-key" | base64
  API_KEY: VGVzdGluZyBTZXJjcmV0
  DB_PASSWORD: REIgUGFzc3dvcmQ=