apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - name: nginx
      image: nginx:1.27.5-alpine
      ports:
      - name: http
        containerPort: 80
      volumeMounts:
      - name: myapp-cm
        mountPath: /etc/nginx
      - name: myapp-vol
        mountPath: /usr/share/nginx/html
  volumes:
  - name: myapp-cm
    configMap:
      name: myapp-cm
  - name: myapp-vol
    hostPath:
      path: /var/nginx/html
      type: DirectoryOrCreate